### ISSUE TITLE
Issue with links that point to page anchors

### ISSUE THREAD

**Issue by SeiferTim** [HaxeFlixel/snippets.haxeflixel.com#38]
Noticed on https://snippets.haxeflixel.com/tiles/autotiles/

The links that go to pages work, but if it should be an anchor on a page, like 
"customTileRemap" it links to 

`https://api.haxeflixel.com/flixel/tile/FlxBaseTilemap/customTileRemap.html`

When it Should link to

`https://api.haxeflixel.com/flixel/tile/FlxBaseTilemap.html#customTileRemap`

**Comment by Geokureli** [comment]
worth noting here that on this page, links for [FlxTilemapAutoTiling.AUTO](https://api.haxeflixel.com/flixel/tile/FlxBaseTilemap/FlxTilemapAutoTiling.html#AUTO) are wrong because this type was moved from `flixel.tile.FlxBaseTilemap.FlxTilemapAutoTiling` to `flixel.tile.FlxTilemapAutoTiling`, so these are an easy fix.

The link you refer to, however, seems like a gnarly bug with the interpreter. it seems to think that customTileRemap is a class in the FlxBaseTilemap package. For now I will temp fix this by using literal url link, but I need to look into how these api tags are interpreted, so this issue should stay open

**Comment by Geokureli** [comment]
@SeiferTim The page is fixed, the issue that caused it is still happening, and will be tracked in issue 39
